# Generated by Django 6.1 on 2026-08-15 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAiderMarshal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('first_aider', 'First aider'), ('fire_marshal', 'Fire marshal'), ('both', 'First aider & Fire marshal')], default='first_aider', max_length=20)),
                ('certified_on', models.DateField(blank=True, null=True)),
                ('certificate_expiry', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_aiders', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.site')),
            ],
        ),
        migrations.CreateModel(
            name='OSHCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('represents', models.CharField(blank=True, help_text='Management or Workers', max_length=150)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('course_title', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('completed_on', models.DateField(default=django.utils.timezone.now)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-completed_on'],
            },
        ),
    ]
