# Generated by Django 6.1.1 on 2026-09-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstaidermarshal',
            options={'ordering': ['employee_name']},
        ),
        migrations.AlterModelOptions(
            name='oshcommitteemember',
            options={'ordering': ['employee_name']},
        ),
    ]
