# Generated by Django 6.1 on 2026-08-15 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DOSHSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('annual_return', 'Annual return'), ('incident_filing', 'Incident filing (DOSH 1)'), ('doshs_pack', 'DOSHS compliance pack'), ('other', 'Other')], default='doshs_pack', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='doshs_reports/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doshs_reports', to='organizations.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('statutory_reference', models.CharField(blank=True, help_text='e.g. Fire Risk Reduction Rules 2007', max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('due_soon', 'Due soon'), ('overdue', 'Overdue'), ('done', 'Done')], default='scheduled', max_length=20)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='organizations.organization')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
