# Generated by Django 6.1 on 2026-08-15 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('extinguisher', 'Fire extinguisher'), ('hose_reel', 'Hose reel'), ('alarm', 'Fire alarm'), ('sprinkler', 'Sprinkler'), ('hydrant', 'Hydrant')], default='extinguisher', max_length=20)),
                ('tag_number', models.CharField(help_text='e.g. EXT-IA-012', max_length=50, unique=True)),
                ('location_detail', models.CharField(blank=True, max_length=255)),
                ('last_serviced', models.DateField(blank=True, null=True)),
                ('next_service_due', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_equipment', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.site')),
            ],
            options={
                'ordering': ['tag_number'],
            },
        ),
    ]
