# Generated by Django 6.1.1 on 2026-09-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppeitem',
            options={'ordering': ['name']},
        ),
    ]
