# Generated by Django 6.1 on 2026-08-15 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSafetyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('steps', models.TextField(help_text='One step per line')),
                ('hazards', models.TextField(blank=True)),
                ('ppe_required', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsas', to='organizations.organization')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('hazards_identified', models.TextField(blank=True)),
                ('existing_controls', models.TextField(blank=True)),
                ('likelihood', models.PositiveSmallIntegerField(default=1, help_text='1 (rare) - 5 (almost certain)')),
                ('severity', models.PositiveSmallIntegerField(default=1, help_text='1 (negligible) - 5 (catastrophic)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('due_review', 'Due for review'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.site')),
            ],
        ),
        migrations.CreateModel(
            name='ToolboxTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('held_on', models.DateField(default=django.utils.timezone.now)),
                ('ai_generated', models.BooleanField(default=False, help_text='Generated via AI toolbox talk assistant')),
                ('facilitator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talks', to='organizations.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.site')),
            ],
            options={
                'ordering': ['-held_on'],
            },
        ),
    ]
