# Generated by Django 6.1.1 on 2026-09-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsafetyanalysis',
            options={'ordering': ['-created_at']},
        ),
    ]
