# Generated by Django 6.1.1 on 2026-09-03 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_alter_jobsafetyanalysis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessment',
            options={'ordering': ['-created_at']},
        ),
    ]
