# Generated by Django 6.1 on 2026-08-15 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('injury', 'Injury'), ('near_miss', 'Near miss'), ('property', 'Property damage'), ('environmental', 'Environmental')], default='near_miss', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical / LTI')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('awaiting_dosh', 'Awaiting DOSH filing'), ('closed', 'Closed')], default='open', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_detail', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_lost_time_injury', models.BooleanField(default=False, help_text='Resets the LTI-free day counter')),
                ('dosh_filed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.organization')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.site')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
